# Generated by Django 4.0.4 on 2022-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.IntegerField(choices=[(1, 'Night'), (2, 'Landscape'), (3, 'Urban'), (4, 'Architecture'), (5, 'Portrait'), (6, 'Other')]),
        ),
    ]
