# Generated by Django 4.0.4 on 2022-05-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0002_alter_picture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_picture', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_url',
            field=models.URLField(),
        ),
    ]
