# Generated by Django 4.0.4 on 2022-05-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0003_picture_added_by_alter_picture_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
