# Generated by Django 4.0.4 on 2022-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_alter_picture_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
